config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events, only: [:index, :show]
  get '/welcome', to: 'pages#welcome'
  resources :bookings, only: [:new, :create, :show]
  resources :friends, only: [:new, :create]

  resources :bookings, only: [:index] do
    resources :friends, only: [:new, :create]
  end



  resources :bars, only:[:index, :show, :incoming_event] do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create] do
      get :new_event_booking, on: :collection
    end


    member do
      get :full_map
    end
  end
  get '/full_map_home', to: 'bars#full_map_home'
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :bar_musics, dependent: :destroy
  has_many :musics, through: :bar_musics
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :name, :category, :description, :price, :address_street, :address_zipcode, :address_city, presence: true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    return [address_street, address_zipcode, address_city].compact.join(', ')
  end

  def incoming_event
    self.events.where('date > ?', Time.now).order(date: :asc).first
  end

  def distance_from
    "#{Geocoder::Calculations.distance_between([self.latitude, self.longitude], [46.53214628568322, 6.590972302445458]).round(1)} km"
  end

  def average_rating
    if !self.reviews.empty?
      average_user_array = []
      self.reviews.each do |review|
        average_user_array << ((review.review_experience.to_f + review.review_drink.to_f + review.review_music.to_f)/3)
      end
      sum = 0
      average_user_array.each do |number|
        sum += number
      end
      (sum/(self.reviews.count)).round(0)
    else
      "no ratings"
    end
  end

  def blank_stars
    5 - average_rating.to_i
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :full_map, :full_map_home]

  def index
    if params[:query].present?
      sql_query = "address_city ILIKE :query OR name ILIKE :query"
      @bars = Bar.where(sql_query, query: "%#{params[:query]}%")
    elsif params[:tag_category]
      @bars = Bar.where(category: params[:tag_category])
    elsif params[:tag_terrace]
      @bars = Bar.where(terrace: params[:tag_terrace])
    elsif params[:tag_price]
      @bars = Bar.where(price: params[:tag_price])
    elsif params[:tag_music]
      @bars = Bar.joins(:musics).where( musics: { name: params[:tag_music] } )
    else
      @bars = Bar.all
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @markers = [{
      lat: @bar.latitude,
      lng: @bar.longitude
    }]
    @events = chunk(@bar.events, 2)
    @redirection = params[:redirection]
    @musics = @bar.musics
  end

  def full_map
    @bar = Bar.find(params[:id])
    @markers = [{
      lat: @bar.latitude,
      lng: @bar.longitude
    }]
  end

  def full_map_home
    @bars = Bar.all
    @markers = @bars.map do |bar|
     {
      lat: bar.latitude,
      lng: bar.longitude,
      infoWindow: render_to_string(partial: "bars/info_window", locals: { bar: bar })
     }
    end
  end

  private

  def bar_params
    params.require(:bar).permit(
      :name, :category, :description, :price,
      :address_street, :address_zipcode, :address_city, :user_id
    )
  end

  private

  def chunk(array, chunk_size)
    i = 0
    new_array = []
    array_size = array.size
    while i < array_size
      new_array << array.slice(i ... i + chunk_size)
      i += chunk_size
    end
    return new_array
  end
end

app/views/bars/_card-bar-larg.html.erb
<div class="card-bar-larg">
  <img src="<%= bar.photo_url_1 %>">

  <div class="card-bar-info">
    <% if bar.incoming_event %>
    <div class="card-bar-event">
      <p><%= bar.incoming_event.category %></p>
    </div>
    <% end %>

    <div class="card-bar-title">
      <h5><%= bar.name %></h5>
    </div>

    <div class="card-bar-review-position">
      <div class="card-bar-review">
        <div class="stars">
          <div class="card-bar-show-reviews">
            <% bar.average_rating.to_i.times do %>
              <span class="fas fa-star" style="color: #D83F87;"></span>
            <% end %>
            <% bar.blank_stars.to_i.times do %>
              <span class="fas fa-star" style="color: grey;"></span>
            <% end %>
          </div>
        </div>
      </div>

      <div class="card-bar-larg-position">
        <div class="position-text">
          <i class="fas fa-map-marker-alt" style="color: #78c4d4;"></i>
        </div>

        <div class="position-meter">
          <p><%= bar.distance_from %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bars/_card-event-small.html.erb
<div class="card-event-small">
  <img src="<%= event.photo_url_1 %>">

  <div class="card-event-info">
    <div class="card-event-event">
      <p><%= event.category %></p>
    </div>

    <div class="card-event-title">
      <h5><%= event.name %></h5>
    </div>

    <div class="card-event-position-price">
      <div class="price">
        <%if event.price.to_i == 0  %>
          <p>free</p>
        <% else %>
          <p><%= "#{event.price}.-" %></p>
        <% end %>
      </div>
      <div class="card-event-position">
        <div class="position-text-small">
          <i class="fas fa-map-marker-alt" style="color: #78c4d4;"></i>
        </div>
        <div class="position-meter">
          <p><%= event.bar.distance_from %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bars/_info_window.html.erb
<h6><%= bar.name %></h6>
<p><%= bar.address_street %></p>

app/views/bars/full_map.html.erb
<!-- <h5>View Full Map</h5> -->
<div class="full-map-show">
  <div id="map" class="full_size_map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <%= link_to bar_path(@bar), class: "show-map-back" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
</div>

app/views/bars/full_map_home.html.erb
<!-- <h5>View Full Map</h5> -->
<div class="full-map-show">
  <div id="map" class="full_size_map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <%= link_to root_path, class: "show-map-back" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
</div>

app/views/bars/index.html.erb
<!-- Bar header -->
<%= link_to root_path do %>
  <div class="arrow-back">
    <i class="fas fa-chevron-left"></i>
  </div>
<% end %>

<div class="bar-header">
  <div class="title">
    <h2>
      <% if params[:tag_category].present? %>
        <%= params[:tag_category].pluralize %>
      <% elsif params[:tag_terrace].present? %>
        Terraces
      <% else %>
        Sites
      <% end %>
    </h2>
  </div>
</div>

<div class="index-container">
  <!-- Filters -->
  <div class="filters-index container">
  <!-- Category filter -->
    <div class="btn-group">
      <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </button>
      <div class="dropdown-menu">
        <div><%= link_to "Bar", bars_path(tag_category: "Bar") %></div>
        <div><%= link_to "Pub", bars_path(tag_category: "Pub") %></div>
        <div><%= link_to "Nightclub", bars_path(tag_category: "Nightclub") %></div>
        <div><%= link_to "Lounge", bars_path(tag_category: "Lounge") %></div>
        <div><%= link_to "Rooftop", bars_path(tag_category: "Rooftop") %></div>
        <div><%= link_to "Cocktail Bar", bars_path(tag_category: "Cocktail Bar") %></div>
        <div><%= link_to "Beer Bar", bars_path(tag_category: "Beer Bar") %></div>
        <div><%= link_to "Champagne Bar", bars_path(tag_category: "Champagne Bar") %></div>
        <div><%= link_to "Wine Bar", bars_path(tag_category: "Wine Bar") %></div>
        <div><%= link_to "Sports Bar", bars_path(tag_category: "Sports Bar") %></div>
        <div><%= link_to "Beach Bar", bars_path(tag_category: "Beach Bar") %></div>
        <div><%= link_to "Shisha Bar", bars_path(tag_category: "Shisha Bar") %></div>
        <div><%= link_to "Gay Bar", bars_path(tag_category: "Gay Bar") %></div>
        <div><%= link_to "Adult", bars_path(tag_category: "Adult") %></div>
      </div>
    </div>

    <!-- Price filter -->
    <div class="btn-group">
      <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Prices
      </button>
      <div class="dropdown-menu">
        <div><%= link_to "$", bars_path(tag_price: "$") %></div>
        <div><%= link_to "$$", bars_path(tag_price: "$$") %></div>
        <div><%= link_to "$$$", bars_path(tag_price: "$$$") %></div>
      </div>
    </div>

    <!-- Music style filter -->
    <div class="btn-group">
      <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Music styles
      </button>
      <div class="dropdown-menu">
        <div><%= link_to "Jazz", bars_path(tag_music: "Jazz") %></div>
        <div><%= link_to "Soul", bars_path(tag_music: "Soul") %></div>
        <div><%= link_to "Rock", bars_path(tag_music: "Rock") %></div>
        <div><%= link_to "Pop", bars_path(tag_music: "Pop") %></div>
        <div><%= link_to "Dance / Electro", bars_path(tag_music: "Dance/Electro") %></div>
        <div><%= link_to "Latino", bars_path(tag_music: "Latino") %></div>
        <div><%= link_to "Metal", bars_path(tag_music: "Metal") %></div>
        <div><%= link_to "80s Music", bars_path(tag_music: "80s Music") %></div>
        <div><%= link_to "70s Music", bars_path(tag_music: "70s Music") %></div>
        <div><%= link_to "Indie", bars_path(tag_music: "Indie") %></div>
      </div>
    </div>
  </div>
  <!-- Cards container -->
  <% @bars.each do |bar|  %>
    <%= link_to bar_path(bar, redirection: "bar-index") do %>
      <%= render 'card-bar-larg', bar: bar%>
    <% end %>
  <% end %>
</div>

<%= render 'shared/index-btn' %>

app/views/bars/show.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div id="img-bar-show" class="carousel-inner">
    <div class="carousel-item active p-0">
      <img src="<%= @bar.photo_url_1 %>" class="d-block h-100 w-100">
    </div>
    <div class="carousel-item p-0">
      <img src="<%= @bar.photo_url_2 %>" class="d-block h-100 w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="show-container">
  <div class="card-bar-show">
    <div class="card-bar-show-body">
        <h6 class="card-bar-show-category"><%= @bar.category %></h6>
        <h4><%= @bar.name %></h4>
        <% @musics.each do |music| %>
        <div class="badge badge-pill badge-warning">
         <%= music.name %>
        </div>
      <% end %>
        <h6 class="card-bar-price-grey"><%= @bar.price %></h6>
        <p><%= @bar.description %></p>
        <div class="card-bar-show-reviews">
          <% @bar.average_rating.to_i.times do %>
            <span class="fas fa-star" style="color: #D83F87;"></span>
          <% end %>
          <% @bar.blank_stars.to_i.times do %>
            <span class="fas fa-star" style="color: grey;"></span>
          <% end %>
          <span><%= "#{@bar.average_rating} / 5" %> </span>
        </div>

    </div>
    <div class="card-bar-show-buttons">
      <% if user_signed_in? %>
        <%= link_to "Guest List", new_bar_booking_path(@bar), class: "btn btn-pink" %>
        <%= link_to "Book Table", new_bar_booking_path(@bar), class: "btn btn-outline-pink" %>
      <% else %>
        <%= link_to "Guest List", welcome_path, class: "btn btn-pink" %>
        <%= link_to "Book Table", welcome_path, class: "btn btn-outline-pink" %>
      <% end %>
      <% if @bar.reviews.where(user: current_user).empty?  %>
        <%= link_to "Add Review", new_bar_review_path(@bar), class: "btn btn-outline-pink" %>
      <% end %>
    </div>
  </div>

  <div class= "card-bar-show-map">
    <div id="map" class="small_size_map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <%= link_to full_map_bar_path(@bar), class: "show-map-expand" do %>
      <i class="fas fa-expand-alt"></i>
    <% end %>
  </div>



  <% if @bar.events.empty? == false %>
    <h5 class="section-title">Events</h5>
    <div class="homepage-group">
      <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @events.each do |event_items| %>
            <div class="<%= event_items == @events.first ? 'carousel-item active' : 'carousel-item' %>">
              <div class="splitted">
                <% event_items.each do |event| %>
                  <%= link_to event_path(event, redirection: "home") do %>
                    <%= render "pages/cards/card-event-small", event: event%>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  <% end %>

  <h5 class="section-title">Photos of the night</h5>
  <div class="photos-night">
    <% if  @bar.name == "Mad club"%>
      <img class="photo" src="https://images.unsplash.com/photo-1517620430776-0ec904756579?ixid=MXwxMjA3fDB8MHxzZWFy[…]fHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1586156938613-769b0353c8fc?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1569315618680-3d673b5e1514?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&ixid=MXwxM[…]2hubyUyMGRhbmNlfGVufDB8fDB8&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?ixlib=rb-1.2.1&ixid=MXwxM[…]8OHx8cGFydHl8ZW58MHx8MHw%3D&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1505236858219-8359eb29e329?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1575426158929-59962325660a?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1586972246803-d2bdc4006378?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1566737236500-c8ac43014a67?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
    <% elsif @bar.name == "Le Comptoir Cocktail Bar"  %>
      <img class="photo" src="https://images.unsplash.com/photo-1473177027534-53d906e9abcf?ixlib=rb-1.2.1&ixid=MXwxM[…]mlua2luZ3xlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1597831092859-d55a7cbb92dd?ixid=MXwxMjA3fDB8MHxzZWFy[…]58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1615850806243-ae2c39d5dad5?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1485872299829-c673f5194813?ixid=MXwxMjA3fDB8MHxzZWFy[…]58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1591627065964-858a84b606b4?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1471015060382-6cbd8b4e34d0?ixid=MXwxMjA3fDB8MHxzZWFy[…]fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1585581277915-b996e30ecc13?ixid=MXwxMjA3fDB8MHxzZWFy[…]fHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixid=MXwxMjA3fDB8MHxzZWFy[…]fHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1569937703691-0f9b8cf21a25?ixid=MXwxMjA3fDB8MHxzZWFy[…]fHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
    <% else %>
      <img class="photo" src="https://images.unsplash.com/photo-1485872299829-c673f5194813?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8cGFydHl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1527529482837-4698179dc6ce?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Nnx8cGFydHl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1528495612343-9ca9f4a4de28?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTF8fHBhcnR5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTR8fHBhcnR5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fHBhcnR5fGVufDB8fDB8&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1438557068880-c5f474830377?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjl8fHBhcnR5fGVufDB8fDB8&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1496843916299-590492c751f4?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fHBhcnR5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1586105449897-20b5efeb3233?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjN8fHBhcnR5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
      <img class="photo" src="https://images.unsplash.com/photo-1607504622473-62981bf57d13?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NTB8fHBhcnR5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60" alt="">
    <% end %>

  </div>
</div>