config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events, only: [:index, :show]
  get '/welcome', to: 'pages#welcome'
  resources :bookings, only: [:new, :create, :show]
  resources :friends, only: [:new, :create]

  resources :bookings, only: [:index] do
    resources :friends, only: [:new, :create]
  end



  resources :bars, only:[:index, :show, :incoming_event] do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create] do
      get :new_event_booking, on: :collection
    end


    member do
      get :full_map
    end
  end
  get '/full_map_home', to: 'bars#full_map_home'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bar
  belongs_to :user
  has_many :friends, dependent: :destroy
  validates :date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where("user_id= ?", current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
    @redirection = params[:redirection]
  end

  def new
    @bar = Bar.find(params[:bar_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @bar = Bar.find(params[:bar_id])
    @booking.bar = @bar
    if @booking.save!
      redirect_to new_booking_friend_path(@booking)
    else
      # flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :table_booking?)
  end
end

app/views/bookings/_card-booking.html.erb
<div class="card-booking">
  <% if booking.table_booking? %>
    <div id="table" class="booking-title-card">
      <p><%= "Booking table confirmation"%></p>
    </div>
  <% else %>
    <div id="guest-list" class="booking-title-card">
      <p> <%= "Guest list confirmation" %></p>
    </div>
  <% end %>
  <div class="booking-info">
    <div class="booking-bar-name">
      <%= booking.bar.name%>
    </div>
    <div class="booking-id">
      <div class="booking-id-name">
        <b><%= "#{booking.user.first_name} #{booking.user.last_name}"%></b>
      </div>
  </div>
      <div class="booking-id">
        <%= pluralize booking.friends.count, "Guest" %>
      </div>
    <div class="booking-id-date">
      <b><%= "#{booking.date.strftime('%d %B %Y')} "%></b>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<!-- Bar header -->
<%= link_to root_path do %>
  <div class="arrow-back">
    <i class="fas fa-chevron-left"></i>
  </div>
<% end %>
  <div class="bar-header">
    <div class="title">
      <h2>Messages</h2>
    </div>
  </div>

<div class="index-container">
  <% @bookings.each do |booking|  %>
    <%= link_to booking_path(booking, redirection: "booking-index") do %>
      <%= render 'card-booking', booking: booking%>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="booking-container">
  <div class="booking-forme">
    <div class="cross-back-btn">
      <%= link_to bar_path(@bar) do %>
        <i class="fas fa-times"></i>
      <% end %>
    </div>
    <p class="booking-title">Guest List form for:</p>
    <h2 class="booking-subtitle"> <%= @bar.name %></h2>
    <%= simple_form_for [ @bar, @booking ] do |f| %>
    <div class="table-check">
    <%= f.input :date, label: "Select the day" %>
    <p>Do you want to book a table?</p>
     <div class="form-check">
        <input class="form-check-input" type="radio" name="booking[table_booking?]" value="1" id="table1">
        <label class="form-check-label" for="table1">
          Yes
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="booking[table_booking?]" value="0" id="table2" checked>
        <label class="form-check-label" for="table2">
          No
        </label>
      </div>
    </div>
      <%= f.submit "Add me on Guest List", class: "booking-btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% if @redirection == "booking-index"%>
  <%= link_to bookings_path do %>
    <div class="arrow-back-show">
      <i class="fas fa-chevron-left"></i>
    </div>
  <% end %>
  <% else %>
    <%= link_to root_path do %>
      <div class="arrow-back-show">
        <i class="fas fa-chevron-left"></i>
      </div>
    <% end %>
<% end %>

<div class="img-booking-show">
  <img src="<%= @booking.bar.photo_url_1 %>">
</div>


<% if @booking.table_booking? %>
  <div id="table-show" class="booking-title-show">
    <p><%= "Booking table confirmation"%></p>
  </div>
<% else %>
  <div id="guest-list-show" class="booking-title-show">
    <p> <%= "Guest list confirmation" %></p>
  </div>
<% end %>

<div class="show-container">
  <div class="card-booking-show">
    <div class="card-booking-show-body">
      <div class="card-booking-bar-name">
        <h4><%= @booking.bar.name %></h4>
      </div>

      <div class="booking-id">
        <div class="booking-id-name"><b><%= "#{@booking.user.first_name} #{@booking.user.last_name}"%></b></div>
      </div>

      <div class="booking-id">
        <div id="booking-date"><b><%= @booking.date.strftime('%d %B %Y')%></b> </div>
      </div>

      <div class="guests-list">
        <div>
          <p><%= "#{@booking.friends.count} Guests :" %> </p>
        </div>
        <div>
          <ul>
            <% @booking.friends.each do |friend| %>
                <li>
                  <%= "#{friend.first_name}, #{friend.last_name}" %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div id="booking-date"> Valid until : <b><%= "#{@booking.date.strftime('%d %B %Y')} 12:00 PM"%></b> </div>

    </div>
  </div>
</div>