config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events, only: [:index, :show]
  get '/welcome', to: 'pages#welcome'
  resources :bookings, only: [:new, :create, :show]
  resources :friends, only: [:new, :create]

  resources :bookings, only: [:index] do
    resources :friends, only: [:new, :create]
  end



  resources :bars, only:[:index, :show, :incoming_event] do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create] do
      get :new_event_booking, on: :collection
    end


    member do
      get :full_map
    end
  end
  get '/full_map_home', to: 'bars#full_map_home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_index-btn.html.erb
<div class="btn-filter-map">
  <div class="btn-filter">
    <%= link_to "" do %>
      <%= svg('icon-up') %>
      <p>FILTERS</p>
    <% end %>
  </div>
  <div class="btn-map">
    <%= link_to full_map_home_path do %>
      <i class="fas fa-map-marked-alt"></i>
      <p>MAP</p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-barfever fixed-bottom">
  <% if user_signed_in? %>
    <% if current_user.status == 'I own the party!' %>
      <div class="container-element-navbar">
        <%= link_to root_path do %>
          <%= svg('icon-home') %>
          <p>Home</p>
        <% end %>
      </div>
      <div class="container-element-navbar">
        <%= link_to "#", class:"ml-1" do %>
          <%= svg('icon-bar') %>
          <p>My Site</p>
        <% end %>
      </div>
      <div class="container-element-navbar">
          <%= link_to "#", class:"ml-2" do %>
            <%= svg('icon-event') %>
            <p>My Events</p>
          <% end %>
      </div>
      <div class="container-element-navbar">
          <%= link_to "#", class:"icon-bigger" do %>
            <%= svg('icon-notification') %>
            <p>Messages</p>
          <% end %>
      </div>
      <div class="container-element-navbar dropup">
        <%= link_to "#", class: "icon-bigger dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
          <%= svg('icon-user') %>
          <p>Profile</p>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      </div>
    <% else %>
      <div class="container-element-navbar">
        <%= link_to root_path do %>
          <%= svg('icon-home') %>
          <p>Home</p>
        <% end %>
      </div>
      <div class="container-element-navbar">
        <%= link_to bars_path, class:"ml-1" do %>
          <%= svg('icon-bar') %>
          <p>Sites</p>
        <% end %>
      </div>
      <div class="container-element-navbar">
          <%= link_to events_path, class:"ml-2" do %>
            <%= svg('icon-event') %>
            <p>Events</p>
          <% end %>
      </div>
      <div class="container-element-navbar">
          <%= link_to bookings_path, class:"icon-bigger" do %>
            <%= svg('icon-notification') %>
            <p>Messages</p>
          <% end %>
      </div>
      <div class="container-element-navbar dropup">
        <%= link_to "#", class: "icon-bigger dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
          <%= svg('icon-user') %>
          <p>Profile</p>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      </div>
    <% end %>
  <% else %>
    <div class="container-element-navbar">
      <%= link_to root_path do %>
        <%= svg('icon-home') %>
        <p>Home</p>
      <% end %>
    </div>
    <div class="container-element-navbar">
      <%= link_to bars_path, class:"icon-bigger ml-1" do %>
        <%= svg('icon-bar') %>
        <p>Sites</p>
      <% end %>
    </div>
    <div class="container-element-navbar">
      <%= link_to events_path, class:"ml-2" do %>
        <%= svg('icon-event') %>
        <p>Events</p>
      <% end %>
    </div>
    <div class="container-element-navbar">
      <%= link_to welcome_path, class:"icon-bigger" do %>
        <%= svg('icon-cheers') %>
        <p>Join the party!</p>
      <% end %>
    </div>
  <% end %>
</div>